<?php

declare(strict_types=1);

namespace Codenzia\SuperAdmin\Support;

/**
 * Tiny .env writer. Replaces or appends KEY=VALUE lines while preserving
 * surrounding comments, blank lines, and the file's line-ending convention.
 *
 * Not a full Dotenv parser — handles the 95% case (simple `KEY=value` or
 * `KEY="quoted value"`). Values containing whitespace, `#`, or `"` are
 * auto-quoted with double quotes; embedded double quotes are backslash-
 * escaped. Values without such characters are written unquoted to match
 * the convention of `.env.example` files generated by `laravel new`.
 */
final class EnvWriter
{
    /**
     * Update or insert one or more KEY=VALUE pairs in the .env file at
     * $path. Returns the list of keys that were modified (created or
     * updated).
     *
     * @param  array<string,string|int|float|bool|null>  $pairs
     * @return list<string>
     */
    public static function setMany(string $path, array $pairs): array
    {
        if (! is_file($path)) {
            // Touch a fresh file so we can append to it.
            file_put_contents($path, '');
        }

        $contents = (string) file_get_contents($path);

        // Detect line endings — preserve what's there. Default to LF.
        $eol = str_contains($contents, "\r\n") ? "\r\n" : "\n";
        $lines = preg_split('/\r\n|\r|\n/', $contents) ?: [];

        // Track whether the file ended with a trailing newline so we
        // don't double up.
        $hadTrailingNewline = $contents === '' || preg_match('/(\r\n|\r|\n)$/', $contents) === 1;

        // If preg_split produced a trailing empty element due to a final
        // newline, drop it so we append cleanly.
        if ($hadTrailingNewline && end($lines) === '') {
            array_pop($lines);
        }

        $changed = [];

        foreach ($pairs as $key => $value) {
            $formatted = self::formatValue($value);
            $replaced = false;

            foreach ($lines as $i => $line) {
                if (preg_match('/^\s*'.preg_quote($key, '/').'\s*=/', $line) === 1) {
                    if ($line !== $key.'='.$formatted) {
                        $lines[$i] = $key.'='.$formatted;
                        $changed[] = $key;
                    }
                    $replaced = true;
                    break;
                }
            }

            if (! $replaced) {
                $lines[] = $key.'='.$formatted;
                $changed[] = $key;
            }
        }

        $output = implode($eol, $lines).$eol;
        file_put_contents($path, $output);

        return array_values(array_unique($changed));
    }

    /**
     * Convenience: update one key.
     */
    public static function set(string $path, string $key, mixed $value): bool
    {
        return self::setMany($path, [$key => $value]) !== [];
    }

    private static function formatValue(mixed $value): string
    {
        if ($value === null) {
            return '""';
        }

        if (is_bool($value)) {
            return $value ? 'true' : 'false';
        }

        $string = (string) $value;

        // Quote if the value contains whitespace, # (comment marker), or
        // a quote character itself. Empty strings get quoted too so they
        // round-trip cleanly.
        $needsQuotes = $string === ''
            || preg_match('/[\s"#]/', $string) === 1;

        if (! $needsQuotes) {
            return $string;
        }

        // Escape backslashes first, then double quotes.
        $escaped = str_replace(['\\', '"'], ['\\\\', '\\"'], $string);

        return '"'.$escaped.'"';
    }
}
